---
name: speedtest

networks: # docker network create proxy
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy
    external: true

services:
  speedtest:
    container_name: speedtest
    image: lscr.io/linuxserver/speedtest-tracker:1.5.0
    restart: unless-stopped
    networks:
      - proxy
    env_file: .env
    volumes:
      - "./speedtest/data:/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.entrypoints=https"
      - "traefik.http.routers.speedtest.rule=Host(`speed.local.irishlab.io`)"
      - "traefik.http.routers.spspeedtesteed.service=speedtest"
      - "traefik.http.routers.speedtest.tls=true"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
