---
name: jellyfin

networks: # docker network create proxy
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy
    external: true

services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:10.10.7
    restart: unless-stopped
    networks:
      - proxy
    env_file: .env
    volumes:
      - "./jellyfin/library:/config"
      # - /path/to/tvseries:/data/tvshows
      # - /path/to/movies:/data/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.irishlab.io`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
