---
name: jellyfin

networks: # docker network create proxy
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy
    external: true

volumes:
  movies:
    name: movies
    driver_opts:
      type: nfs
      o: addr=192.168.20.41,nolock,soft,rw
      device: :/mnt/rusty/media/movies
  tv:
    name: tv
    driver_opts:
      type: nfs
      o: addr=192.168.20.41,nolock,soft,rw
      device: :/mnt/rusty/media/tv

services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:10.10.7
    restart: unless-stopped
    networks:
      - proxy
    env_file: .env
    volumes:
      - "./jellyfin/library:/config"
      - "movies:/data/movies"
      - "tv:/data/tv"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.irishlab.io`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
