---
name: qbittorrent

networks:
  gluetun:
    name: gluetun
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy
    external: true

services:

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    networks:
      - gluetun
    ports:
      - "8080:8080"
      # - "6881:6881 "# already mapped by gluetun
      # - "6881:6881/udp" # already mapped by gluetun
    env_file: .env
    volumes:
      - "./config:/config"
