---
- name: Secret | Hello first task
  ansible.builtin.debug:
    msg: Hello first task ran without any issue.

- name: Echo secret
  ansible.builtin.debug:
    msg: "Secret value is: {{ secret_token_tailscale }}"
