---
name: gotify

networks: # docker network create proxy
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy
    external: true

services:
  gotify:
    container_name: gotify
    image: gotify/server:2.6.3
    restart: unless-stopped
    networks:
      - proxy
    env_file: .env
    volumes:
      - './gotify_data:/app/data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.rule=Host(`gotify.local.irishlab.io`)"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
