---
name: pihole

networks: # docker network create proxy
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy
    external: true

services:
  pihole:
    container_name: pihole
    image: ghcr.io/pi-hole/pihole:2025.04.0
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    env_file: .env
    cap_add:
      - SYS_TIME
      - SYS_NICE
    volumes:
      - "./pihole:/etc/pihole"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.pihole-prefix.addPrefix.prefix=/admin"
      - "traefik.http.middlewares.pihole.addprefix.prefix=/admin"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.middlewares=pihole-prefix"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local.irishlab.io`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
