---
name: whisparr

networks: # docker network create proxy
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy
    external: true

volumes:
  downloads:
    name: downloads
    driver_opts:
      type: nfs
      o: addr=192.168.20.41,nolock,soft,rw
      device: :/mnt/rusty/downloads/
  porn:
    name: porn
    driver_opts:
      type: nfs
      o: addr=192.168.20.41,nolock,soft,rw
      device: :/mnt/rusty/media/porn

services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:v3-3.0.0.530
    restart: unless-stopped
    networks:
      - proxy
    env_file: .env
    volumes:
      - "./config:/config"
      - "porn:/porn"
      - "downloads:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisparr.entrypoints=https"
      - "traefik.http.routers.whisparr.rule=Host(`whisparr.local.irishlab.io`)"
      - "traefik.http.routers.whisparr.tls=true"
      - "traefik.http.services.whisparr.loadbalancer.server.port=6969"
