---
- name: Docker | Echo secret
  ansible.builtin.debug:
    msg: "Secret value is: {{ lookup('bitwarden.secrets.lookup', docker_id_tailscale) }}"

# - name: Packages | Install common packages
#   ansible.builtin.apt:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - curl
