---
- name: Provision secret
  hosts:
    - localhost
  connection: local
  any_errors_fatal: true
  pre_tasks:
    - name: Status message
      ansible.builtin.debug:
        msg: Playbook will now run.
  roles:
    - role: secret
  post_tasks:
    - name: Status message
      ansible.builtin.debug:
        msg: Playbook ran without any issue.
