baseURL = "https://www.irishlab.io"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "irishlab.io"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
    menu_style = "slide-menu"
    description = "This is my homelab, there are many like this but this one is mine."

    dateformat = "" # default "2 Jan 2006"

    github_repository = "https://github.com/irishlab-io/irishlab"
    github_doc_repository = "https://github.com/irishlab-io/irishlab"
    github_doc_repository_branch = "main"
    github_doc_repository_path = "irishlab/docs/content/"

    # Analytic section
    # google_analytics_id = "" # Your Google Analytics tracking id
    # tag_manager_container_id = "" # Your Google Tag Manager container id
    # google_site_verification = "" # Your Google Site Verification for Search Console

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable = true
    algolia_indexName = "hugo-demo-techdoc"
    algolia_appId = "7W4SAN4PLK"
    algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

# Global menu section
[menu]
    [[menu.main]]
        name = ""
        url = "/"
        weight = 1
        identifier = 'home'

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
